# Environment Args
output_root: '/home/icb/paul.volk/rbc_upsampling_comparision'
pytorch_data_dir: '/home/icb/paul.volk/data/Elsafty_selected' #/ictstr01/groups/labs/marr/qscd01/workspace/rao.umer/pengmarr_hackathon_2023/datasets/
submitting_to_aml: false
summarize: true
experiment_name: "rbc_implicit_upsampler"

# Dataset args
dataset: "custom"
split: "test"
partition: 0
total_partitions: 1

# Model Args
model_type: "dino16" # dino16, dinov2, vit, dinobloom, directsam2
activation_type: "token"

# Upsampler args
outlier_detection: True
downsampler_type: "attention"
blur_attn: True
mag_tv_weight: 0.05
mag_weight: 0.001
color_feats: true
pca_batch: 50
proj_dim: 128
max_pad: 30
use_flips: true
max_zoom: 1.8
blur_pin: 0.1
n_freqs: 30
param_type: "implicit"
use_norm: false

# Training args
steps: 2001 # 1200
n_images: 3000

# No need to change
hydra:
  run:
    dir: "."
  output_subdir: ~

